### ISSUE TITLE
Is there a document or any others that explains the basis and source of all validators?

### ISSUE THREAD

**Issue by zzzsz** [digicert/pkilint#102]
Is there a document or any others that explains the basis and source of all validators?

For example, to indicate that a validator is from section x.x.x of the RFC.

**Comment by CBonnell** [comment]
Hi @zzzsz,
For the CABF S/MIME and TLS BR validations, there are finding_metadata.csv files in the source tree.

More easily discoverable citations are planned to resolve #64.

**Comment by CBonnell** [comment]
Closing; better documentation will be provided as part of #64.
