### ISSUE TITLE
Gauging interest in niche certificate profiles (ETSI / Eidas / NL)

### ISSUE THREAD

**Issue by breynders-cb** [digicert/pkilint#124]
Internally we'll be going to extending a linter (1 or more) with additional rules to check all cases relevant to our use case. We're a QTSP in the Netherlands and are interested in linting a very specific certificate profile, namely a certificate for natural person qualified signatures ([G4 Individual Validated eSig](https://cp.pkioverheid.nl/pkioverheid-por-v5.0.html#id__716-certificate-policy-object-identifier)).

Other than some pkio (Dutch government pki) rules it's mostly a combination of common rulesets and ETSI rules, namely `NCP+ (0.4.0.2042.1.2)` and `QCP-n-qscd (0.4.0.194112.1.2)`. 

Is there interest in having these rules (partially) merged back upstream? How would you suggest formatting such rules in the current codebase?

**Comment by CBonnell** [comment]
Hi @breynders-cb, thank you for filing this. We would be excited to work with you on adding this support.

pkilint already has comprehensive support for linting QWACs, so many of the lints for the EN 319 412 document series are already in place. Expanding on that support to encompass the NCP+ and QCP-n-qscd profiles would not be very difficult. Once such support is in place, PKIO-specific lints can be added on top rather easily.

I'm open to either collaborating on this Github issue or via email (my email can be found in the contact information for the pkilint maintainer), whichever you prefer.

**Comment by breynders-cb** [comment]
Thanks for the fast response! We'll get started with some basic rules, I'll ask questions either in a properly scoped issue, through email or through PR.

**Comment by digirenpeter** [comment]
@breynders-cb Great to hear that there's interest in the PKIO-specific lints! Coincidentally, we're also in the process of adding PKIO lints to PKIlint. To avoid duplicating efforts, would you be open to sharing more details about the profiles you're planning to implement and your timeline?

**Comment by breynders-cb** [comment]
Awesome to hear that there's more interest!

We're going to focus on check and adding some ETSI rules that are used for our PKIO usecase namely the profiles:
- NCP+ (0.4.0.2042.1.2)
- QCP-n-qscd (0.4.0.194112.1.2)

We'll focus on extending 411-1, 411-2 and 412-2 first. We don't have a timeline yet but are starting work on it in the coming days.
