### ISSUE TITLE
Unknown CN value source

### ISSUE THREAD

**Issue by PeterMiskovic** [digicert/pkilint#13]
When we used pklint to test our new profile for SMIME certificate for ORGANIZATION and STRICT profile type, we got this error:
 _cabf.smime.common_name_value_unknown_source (ERROR): Unknown CN value source: "Disig, a.s."_

Our test file is attached.

Can you explain to us what this error means?

[SMIME_PO_Test_20230620.zip](https://github.com/digicert/pkilint/files/11891153/SMIME_PO_Test_20230620.zip)

Regards
Peter Miskovic

**Comment by CBonnell** [comment]
Hi Peter,
Thank you for reporting this. The common name validator was not performing the comparison of O and CN values correctly, which caused incorrect findings to be raised. I have fixed this issue and released v0.8.6. Please update to the latest version and let me know if it resolves the issue for you.
