### ISSUE TITLE
Add detection of SKI calculation methods described in RFC 7093 to SubjectKeyIdentifierValidator

### ISSUE THREAD

**Issue by CBonnell** [digicert/pkilint#56]
Now that it appears at least one publicly trusted CA will be using one of the methods described in RFC 7093 for SKI calculation [1], SubjectKeyIdentifierValidator should be updated to detect the usage of these methods.

[1] https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/L7XoAXt_s1c/m/Hil4RxrYAAAJ

**Comment by aarongable** [comment]
Heh, I just came here to file this same issue. Thanks!

**Comment by CBonnell** [comment]
v0.9.9 will implement detection of the first three methods defined in RFC 7093. Implementing the fourth method is a challenge due to any hash algorithm being allowed.

Will revisit the decision to not implement detection of method 4 if any adoption of the method is seen.
