### ISSUE TITLE
Provide REST API for linting CRLs

### ISSUE THREAD

**Issue by aarongable** [digicert/pkilint#75]
I'm adding pkilint to our integration test environment, to show that the signed artifacts produced during testing lint cleanly. We already use docker-compose, so simply adding the pkilint docker container to our setup and making http requests to it seemed like the easiest solution.

However, the REST API does not appear to have endpoints for linting CRLs, which means we need to install pkilint directly in our primary container to accomplish that task. It would be great for the CLI and API to have the exact same set of capabilities.

**Comment by CBonnell** [comment]
Thanks for the suggestion, @aarongable. This shouldn't be too heavy of a lift, as similar work was done very recently by @mans-andersson to add REST API support for OCSP response linting.

I'll look to get this added soon.

**Comment by dipaktilekar** [comment]
@CBonnell , @aarongable I have created a PR for this enhancement.
https://github.com/digicert/pkilint/pull/113
Please review and let me know if any comments.

**Comment by robstradling** [comment]
Shameless plug...but...
Another option you could consider is [pkimetal](https://github.com/pkimetal/pkimetal), which (amongst other things) integrates the CRL linting capabilities of both pkilint and Zlint behind a REST API.

**Comment by CBonnell** [comment]
> @CBonnell , @aarongable I have created a PR for this enhancement. #113 Please review and let me know if any comments.

Thank you for your contribution, @dipaktilekar! I'll review your PR by end of the day tomorrow. Barring any major changes, this can probably be included in the next release, slated for later this week.

**Comment by dipaktilekar** [comment]
> Shameless plug...but... Another option you could consider is [pkimetal](https://github.com/pkimetal/pkimetal), which (amongst other things) integrates the CRL linting capabilities of both pkilint and Zlint behind a REST API.

sure, thank you for the suggestion.

**Comment by CBonnell** [comment]
Resolved by #113.
