### ISSUE TITLE
S/MIME linter raises ERROR-level cabf.critical_crldp_extension while SMBR text is SHOULD-level

### ISSUE THREAD

**Issue by CBonnell** [digicert/pkilint#8]
Not sure if intentional or not, but the SMBRs have a SHOULD NOT-level prohibition on making the CRLDP extension critical, whereas it's a MUST NOT for TLS and code signing.

We should raise this in the SMCWG and see whether this deviation from the other BR docs is intentional and make the appropriate changes here (if needed).

**Comment by XolphinMartijn** [comment]
Looks like https://github.com/cabforum/smime/blame/d67de479a039a25c2b97e83a28c60d4c825ceb7d/SBR.md#L915 was the last version that had Critical set to No, in a table version. After this, it was made into a SHOULD NOT, probably by oversight.
