### ISSUE TITLE
What are valid LDAP URLs?

### ISSUE THREAD

**Issue by zzzsz** [digicert/pkilint#97]
In general_name.py, I saw the following code:

   ```
def validate_value(self, node):
        value = str(node.pdu)
        if value.casefold().startswith('ldap://'.casefold()):
            raise validation.ValidationFindingEncountered(self.VALIDATION_LDAP_URI_NOT_VALIDATED, value)
```

This means that if the ldap URL starts with ‘ldap://’, an error will be reported.

And I have conducted an experiment. If the Issuing Distribution Point field of CRL contains the following ldap URL 'ldap://ldapcomp.cert.fnmt.es/CN=CRL1,OU=AC%20Componentes%20Informaticos,O=FNMT-RCM,C=ES?certificateRevocationList;binary?base?objectclass=cRLDistributionPoint', then this error will appear. But this is indeed a correct URL. I can directly use the 'curl' command to obtain the CRL through this URL.

**Comment by CBonnell** [comment]
Hi @zzzsz,
That finding is a NOTICE-level finding that indicates the validator does not check the syntax of LDAP URIs. It is not an indication that the LDAP URI has incorrect syntax (such a finding would be ERROR-level).

When I originally added that finding, my intention was to add a proper LDAP URI validator. However, given that several policies are prohibiting LDAP URIs (S/MIME BR being the latest), I'm not sure of the value of such a check.

**Comment by zzzsz** [comment]
> Hi @zzzsz, That finding is a NOTICE-level finding that indicates the validator does not check the syntax of LDAP URIs. It is not an indication that the LDAP URI has incorrect syntax (such a finding would be ERROR-level).
> 
> When I originally added that finding, my intention was to add a proper LDAP URI validator. However, given that several policies are prohibiting LDAP URIs (S/MIME BR being the latest), I'm not sure of the value of such a check.
> 
> Does this information help resolve this question?

Yes, thank you.
